services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: qsdata
    volumes:
      - db-data:/var/lib/postgresql/data
    # Database port exposure for local development
    ports:
      - '5432:5432'
  server:
    image: node:18
    working_dir: /app
    command: sh -c "npm install && npm run client:build && npm run dev"
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/qsdata
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=qsdata
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
  client:
    image: node:18
    working_dir: /app
    command: sh -c "npm install && npm run client"
    volumes:
      - .:/app
    ports:
      - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=1
    depends_on:
      - server
volumes:
  db-data:
