version: '3'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qsdata
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  server:
    build: .
    command: node index.js
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/qsdata
    depends_on:
      - db
volumes:
  db-data:
