#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const envContent = `# Development Environment Variables
# Generated by setup-dev.js

# JWT Secret (for development only)
JWT_SECRET=dev-secret-key-change-in-production

# Database Configuration
DATABASE_URL=postgres://postgres:devpassword@db:5432/qsdata
POSTGRES_PASSWORD=devpassword

# CORS Configuration (for development)
CLIENT_ORIGIN=http://localhost:5173

# Application Settings
NODE_ENV=development
PORT=3000

# Rate Limiting
RATE_LIMIT_WINDOW_MS=60000
RATE_LIMIT_MAX_REQUESTS=100
`;

const envPath = path.join(__dirname, '..', '.env');

try {
  if (!fs.existsSync(envPath)) {
    fs.writeFileSync(envPath, envContent);
    console.log('✅ Created .env file with development settings');
    console.log('');
    console.log('📝 Development Login Credentials:');
    console.log('   Username: admin, Password: admin');
    console.log('   Username: user, Password: user');
    console.log('');
    console.log('🚀 You can now run: docker-compose -f docker-compose.dev.yml up --build');
  } else {
    console.log('⚠️  .env file already exists. Skipping creation.');
  }
} catch (error) {
  console.error('❌ Error creating .env file:', error.message);
  process.exit(1);
} 